<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('user_details')->insert([
            [
                'user_id' => 1,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '123456789',
                'designation' => 'System Admin',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => null,
            ],
            [
                'user_id' => 2,
                'nin_number' => '123456789',
                'gender' => 'female',
                'phone_number' => '123456789',
                'designation' => 'Head of Service',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 3,
            ],
            [
                'user_id' => 3,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '123456789',
                'designation' => 'Permanent Secretary',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => 2,
                'tenant_id' => 3,
            ],
            [
                'user_id' => 4,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '123456789',
                'designation' => 'User',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => null,
            ],
            [
                'user_id' => 5,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '123456789',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 4,
            ],
            [
                'user_id' => 6,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 5,
            ],
            [
                'user_id' => 7,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 6,
            ],
            [
                'user_id' => 8,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 7,
            ],
            [
                'user_id' => 9,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 8,
            ],
            [
                'user_id' => 10,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 9,
            ],
            [
                'user_id' => 11,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 10,
            ],
            [
                'user_id' => 12,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 11,
            ],
            [
                'user_id' => 13,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 12,
            ],
            [
                'user_id' => 14,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 13,
            ],
            [
                'user_id' => 15,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 14,
            ],
            [
                'user_id' => 16,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 15,
            ],
            [
                'user_id' => 17,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 16,
            ],
            [
                'user_id' => 18,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 17,
            ],
            [
                'user_id' => 19,
                'nin_number' => '123456789',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 18,
            ],
        ]);
    }
}
